CREATE TABLE orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    consecutive VARCHAR(15) NOT NULL UNIQUE,
    id_origin INT NOT NULL,
    id_destination INT NOT NULL,
    id_vehicle INT,
    id_driver INT,
    id_status INT NOT NULL,
    id_client INT NOT NULL,
    id_sender INT NOT NULL,
    id_receiver INT NOT NULL,
    commitment_date DATE NOT NULL,
    delivery_date DATE,
    delivery_time TIME,
    id_user_create INT NOT NULL,
    id_user_update INT DEFAULT NULL,
    id_user_delete INT DEFAULT NULL,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_user_create FOREIGN KEY (id_user_create) REFERENCES users(id),
    CONSTRAINT fk_orders_user_update FOREIGN KEY (id_user_update) REFERENCES users(id),
    CONSTRAINT fk_orders_user_delete FOREIGN KEY (id_user_delete) REFERENCES users(id)
);