version: "3.9"
services:
 mysql:
        image: mysql:8.0
        container_name: envios-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: envios_master
            MYSQL_USER: admin
            MYSQL_PASSWORD: 1234
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        restart: always
volumes:
    mysql_data:
        driver: local

networks:
  default:
    name: envios-network
    external: true